INFO 07-21 19:36:10 [__init__.py:243] Automatically detected platform cuda.
INFO 07-21 19:36:17 [__init__.py:31] Available plugins for group vllm.general_plugins:
INFO 07-21 19:36:17 [__init__.py:33] - lora_filesystem_resolver -> vllm.plugins.lora_resolvers.filesystem_resolver:register_filesystem_resolver
INFO 07-21 19:36:17 [__init__.py:36] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
INFO 07-21 19:36:17 [api_server.py:1289] vLLM API server version 0.9.0.1
INFO 07-21 19:36:18 [cli_args.py:300] non-default args: {'max_model_len': 8192, 'block_size': 16, 'gpu_memory_utilization': 0.91, 'kv_cache_dtype': 'fp8', 'max_num_batched_tokens': 16384, 'max_num_partial_prefills': 4, 'cuda_graph_sizes': [1096], 'long_prefill_token_threshold': 2048, 'enable_chunked_prefill': True, 'compilation_config': {"level": 3, "inductor_compile_config": {"enable_auto_functionalized_v2": false}}, 'disable_log_requests': True}
INFO 07-21 19:36:33 [config.py:793] This model supports multiple tasks: {'score', 'embed', 'generate', 'reward', 'classify'}. Defaulting to 'generate'.
WARNING 07-21 19:36:33 [arg_utils.py:1583] --kv-cache-dtype is not supported by the V1 Engine. Falling back to V0. 
INFO 07-21 19:36:33 [config.py:1503] Using fp8 data type to store kv cache. It reduces the GPU memory footprint and boosts the performance. Meanwhile, it may cause accuracy drop without a proper scaling factor
INFO 07-21 19:36:33 [config.py:2118] Chunked prefill is enabled with max_num_batched_tokens=16384.
INFO 07-21 19:36:33 [config.py:2128] Concurrent partial prefills enabled with max_num_partial_prefills=4, max_long_partial_prefills=1, long_prefill_token_threshold=2048
INFO 07-21 19:36:33 [api_server.py:257] Started engine process with PID 153794
INFO 07-21 19:36:37 [__init__.py:243] Automatically detected platform cuda.
INFO 07-21 19:36:39 [__init__.py:31] Available plugins for group vllm.general_plugins:
INFO 07-21 19:36:39 [__init__.py:33] - lora_filesystem_resolver -> vllm.plugins.lora_resolvers.filesystem_resolver:register_filesystem_resolver
INFO 07-21 19:36:39 [__init__.py:36] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
INFO 07-21 19:36:39 [llm_engine.py:230] Initializing a V0 LLM engine (v0.9.0.1) with config: model='meta-llama/Llama-3.1-8B', speculative_config=None, tokenizer='meta-llama/Llama-3.1-8B', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=8192, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=fp8,  device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=meta-llama/Llama-3.1-8B, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=None, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level": 3, "compile_sizes": [], "inductor_compile_config": {"enable_auto_functionalized_v2": false}, "cudagraph_capture_sizes": [256, 248, 240, 232, 224, 216, 208, 200, 192, 184, 176, 168, 160, 152, 144, 136, 128, 120, 112, 104, 96, 88, 80, 72, 64, 56, 48, 40, 32, 24, 16, 8, 4, 2, 1], "max_capture_size": 256}, use_cached_outputs=True, 
INFO 07-21 19:36:47 [cuda.py:273] Cannot use FlashAttention backend for FP8 KV cache.
WARNING 07-21 19:36:47 [cuda.py:275] Please use FlashInfer backend with FP8 KV Cache for better performance by setting environment variable VLLM_ATTENTION_BACKEND=FLASHINFER
INFO 07-21 19:36:47 [cuda.py:289] Using XFormers backend.
INFO 07-21 19:36:47 [parallel_state.py:1064] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
INFO 07-21 19:36:47 [model_runner.py:1170] Starting to load model meta-llama/Llama-3.1-8B...
INFO 07-21 19:36:47 [backends.py:35] Using InductorAdaptor
INFO 07-21 19:36:49 [weight_utils.py:291] Using model weights format ['*.safetensors']
INFO 07-21 19:36:49 [weight_utils.py:307] Time spent downloading weights for meta-llama/Llama-3.1-8B: 0.583567 seconds
Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:00<00:00,  6.69it/s]
Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:00<00:00,  2.14it/s]
Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:01<00:00,  1.71it/s]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:02<00:00,  1.56it/s]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:02<00:00,  1.75it/s]

INFO 07-21 19:36:52 [default_loader.py:280] Loading weights took 2.34 seconds
INFO 07-21 19:36:52 [model_runner.py:1202] Model loading took 14.9889 GiB and 4.763053 seconds
INFO 07-21 19:36:58 [backends.py:459] Using cache directory: /root/.cache/vllm/torch_compile_cache/564e6876bf/rank_0_0 for vLLM's torch.compile
INFO 07-21 19:36:58 [backends.py:469] Dynamo bytecode transform time: 5.62 s
INFO 07-21 19:37:25 [backends.py:158] Cache the graph of shape None for later use
INFO 07-21 19:37:25 [backends.py:170] Compiling a graph for general shape takes 24.56 s
INFO 07-21 19:37:29 [monitor.py:33] torch.compile takes 30.19 s in total
INFO 07-21 19:37:32 [worker.py:291] Memory profiling takes 39.08 seconds
INFO 07-21 19:37:32 [worker.py:291] the current vLLM instance can use total_gpu_memory (44.52GiB) x gpu_memory_utilization (0.91) = 40.51GiB
INFO 07-21 19:37:32 [worker.py:291] model weights take 14.99GiB; non_torch_memory takes 0.08GiB; PyTorch activation peak memory takes 2.54GiB; the rest of the memory reserved for KV Cache is 22.90GiB.
INFO 07-21 19:37:32 [executor_base.py:112] # cuda blocks: 23450, # CPU blocks: 4096
INFO 07-21 19:37:32 [executor_base.py:117] Maximum concurrency for 8192 tokens per request: 45.80x
INFO 07-21 19:37:33 [model_runner.py:1512] Capturing cudagraphs for decoding. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI. If out-of-memory error occurs during cudagraph capture, consider decreasing `gpu_memory_utilization` or switching to eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
Capturing CUDA graph shapes:   0%|          | 0/35 [00:00<?, ?it/s]Capturing CUDA graph shapes:   3%|▎         | 1/35 [00:00<00:30,  1.13it/s]Capturing CUDA graph shapes:   6%|▌         | 2/35 [00:01<00:27,  1.18it/s]Capturing CUDA graph shapes:   9%|▊         | 3/35 [00:02<00:27,  1.17it/s]Capturing CUDA graph shapes:  11%|█▏        | 4/35 [00:03<00:26,  1.18it/s]Capturing CUDA graph shapes:  14%|█▍        | 5/35 [00:04<00:25,  1.17it/s]Capturing CUDA graph shapes:  17%|█▋        | 6/35 [00:05<00:24,  1.17it/s]Capturing CUDA graph shapes:  20%|██        | 7/35 [00:05<00:24,  1.17it/s]Capturing CUDA graph shapes:  23%|██▎       | 8/35 [00:06<00:22,  1.18it/s]Traceback (most recent call last):
  File "/root/rehan/.venv/bin/vllm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/rehan/.venv/lib/python3.12/site-packages/vllm/entrypoints/cli/main.py", line 56, in main
    args.dispatch_function(args)
  File "/root/rehan/.venv/lib/python3.12/site-packages/vllm/entrypoints/cli/serve.py", line 42, in cmd
    uvloop.run(run_server(args))
  File "/root/rehan/.venv/lib/python3.12/site-packages/uvloop/__init__.py", line 109, in run
    return __asyncio.run(
           ^^^^^^^^^^^^^^
  File "/root/.local/share/uv/python/cpython-3.12.10-linux-x86_64-gnu/lib/python3.12/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/root/.local/share/uv/python/cpython-3.12.10-linux-x86_64-gnu/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/root/rehan/.venv/lib/python3.12/site-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
           ^^^^^^^^^^
  File "/root/rehan/.venv/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 1324, in run_server
    async with build_async_engine_client(args) as engine_client:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/uv/python/cpython-3.12.10-linux-x86_64-gnu/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/rehan/.venv/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 153, in build_async_engine_client
    async with build_async_engine_client_from_engine_args(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/uv/python/cpython-3.12.10-linux-x86_64-gnu/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/rehan/.venv/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 280, in build_async_engine_client_from_engine_args
    raise RuntimeError(
RuntimeError: Engine process failed to start. See stack trace for the root cause.
/root/.local/share/uv/python/cpython-3.12.10-linux-x86_64-gnu/lib/python3.12/multiprocessing/resource_tracker.py:279: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
